# Base information
baseURL = "https://devmcclu.github.io"
languageCode = "en-us"
title = "Devlin McClure"
theme = "hugo-developer-portfolio"
googleAnalytics = ""

# Remove this when using normally
# themesDir = "../../" 
# `
[module]
  [[module.imports]]
    path = "github.com/samrobbins85/hugo-developer-portfolio"

# Plugins
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/css/uikit.min.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit.min.js"
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit-icons.min.js"


# navigation
[menu]

  [[menu.main]]
  name = "About"
  URL = "about"
  weight=1

#  [[menu.main]]
#  name = "Blog"
#  URL = "blog"
#  weight=2

  [[menu.main]]
  name = "Portfolio"
  URL = "portfolio"
  weight=2

  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight=3


[params]
home = "Home"
# Meta data
description = "The website of Devlin McClure"
author = "Devlin McClure"


  [params.contact]
  enable = true
  formAction = "https://formspree.io/f/xaylbedd" #contact form works with formspree.io

  [params.footer]
  email = "mccluredt@gmail.com"
  address = "Indianapolis, Indiana"
  googlemaps = "https://goo.gl/maps/UH8PSZeTnVRsa6A56"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "rainbow_dash"
    tabWidth = 4

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true
